packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  libxmljs2: true
  prisma: true
  sharp: true
  unrs-resolver: true

packageExtensions:
  expo-font@57.0.1:
    dependencies:
      expo-asset: 57.0.13

overrides:
  expo-constants: 57.0.13
  fast-uri: 4.1.3

minimumReleaseAgeExclude:
  - expo-sharing
  - react-hook-form@7.82.0
  - expo-updates@57.0.12
  - '@expo/config-plugins@57.0.8'
  - expo-sharing@57.0.13
  - '@expo/cli@57.0.17'
  - '@expo/fingerprint@0.20.9'
  - '@expo/local-build-cache-provider@57.0.7'
  - '@expo/metro-config@57.0.9'
  - '@expo/prebuild-config@57.0.13'
  - '@expo/router-server@57.0.7'
  - expo-asset@57.0.13
  - expo-file-system@57.0.5
  - expo-modules-core@57.0.12
  - expo-modules-jsi@57.0.5
  - expo@57.0.15
  - '@expo/metro-runtime@57.0.12'
  - '@expo/ui@57.0.12'
  - expo-constants@57.0.13
  - expo-image-picker@57.0.12
  - expo-linking@57.0.7
  - expo-location@57.0.12
  - expo-notifications@57.0.13
  - expo-router@57.0.15
  - expo-sharing@57.0.14
