packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true

minimumReleaseAgeExclude:
  - react-hook-form@7.82.0
  - expo-updates@57.0.12
  - '@expo/config-plugins@57.0.8'
  - expo-sharing@57.0.12
