export const membershipRoles = [
  'owner',
  'manager',
  'receptionist',
  'barber',
] as const;
export type MembershipRole = (typeof membershipRoles)[number];

export const organizationPermissions = [
  'organization.read',
  'organization.update',
  'location.read',
  'location.update',
  'membership.read',
  'membership.manage',
  'service.read',
  'service.manage',
  'schedule.read',
  'schedule.manage',
  'appointment.read',
  'appointment.manage',
  'client.directory.read',
  'client.record.read',
  'client.contact.read_full',
  'client.contact.read_masked',
  'client.personal_data.read',
  'client.create',
  'client.update',
  'client.delete',
  'client.note.read',
  'client.note.create',
  'client.note.manage',
  'client.label.read',
  'client.label.manage',
  'client.export',
  'client.contacts.import',
  'client.communication.initiate',
] as const;
export type OrganizationPermission = (typeof organizationPermissions)[number];

const permissionsByRole = {
  owner: organizationPermissions,
  manager: [
    'organization.read',
    'organization.update',
    'location.read',
    'location.update',
    'membership.read',
    'service.read',
    'service.manage',
    'schedule.read',
    'schedule.manage',
    'appointment.read',
    'appointment.manage',
    'client.directory.read',
    'client.record.read',
    'client.contact.read_full',
    'client.contact.read_masked',
    'client.personal_data.read',
    'client.create',
    'client.update',
    'client.delete',
    'client.note.read',
    'client.note.create',
    'client.note.manage',
    'client.label.read',
    'client.label.manage',
    'client.contacts.import',
    'client.communication.initiate',
  ],
  receptionist: [
    'organization.read',
    'location.read',
    'membership.read',
    'service.read',
    'schedule.read',
    'appointment.read',
    'appointment.manage',
    'client.directory.read',
    'client.record.read',
    'client.contact.read_masked',
  ],
  barber: [
    'organization.read',
    'location.read',
    'service.read',
    'schedule.read',
    'appointment.read',
    'appointment.manage',
    'client.directory.read',
    'client.record.read',
    'client.contact.read_masked',
    'client.note.read',
    'client.note.create',
  ],
} as const satisfies Record<MembershipRole, readonly OrganizationPermission[]>;

export function hasPermission(
  role: MembershipRole,
  permission: OrganizationPermission,
): boolean {
  return (
    permissionsByRole[role] as readonly OrganizationPermission[]
  ).includes(permission);
}
