import { StyleSheet } from 'react-native';

import {
  appStyles,
  appTheme,
  goldButtonShadow,
  goldShadow,
} from './BottomNavigation';

export const s = StyleSheet.create({
  art: { ...StyleSheet.absoluteFill, overflow: 'hidden' },
  back: { marginBottom: 14 },
  backdrop: {
    ...StyleSheet.absoluteFill,
    backgroundColor: appTheme.colors.overlay,
  },
  backText: {
    color: appTheme.colors.accentDark,
    fontSize: 16,
    fontWeight: '700',
  },
  bottom: {
    bottom: -245,
    height: 460,
    left: -80,
    opacity: 0.72,
    transform: [{ rotate: '-28deg' }],
    width: 620,
  },
  button: {
    backgroundColor: appTheme.colors.surface,
    borderWidth: 0,
    flexBasis: 'auto',
    flexGrow: 0,
    flexShrink: 0,
    height: 72,
    marginTop: 22,
    paddingHorizontal: 18,
    width: '100%',
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  choice: { alignItems: 'center', paddingTop: 28, width: '100%' },
  choiceActions: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 22,
    width: '100%',
  },
  choiceButton: {
    backgroundColor: appTheme.colors.surface,
    borderWidth: 0,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  content: { paddingBottom: 0 },
  description: {
    color: appTheme.colors.textMuted,
    fontSize: 16,
    lineHeight: 23,
    marginTop: 7,
  },
  edit: {
    color: appTheme.colors.accentDark,
    fontSize: 14,
    fontWeight: '800',
  },
  error: {
    color: appTheme.colors.dangerBorder,
    fontSize: 13,
    marginTop: 5,
  },
  field: { marginBottom: 15 },
  fields: { marginTop: 18 },
  formError: {
    backgroundColor: appTheme.colors.dangerSurface,
    borderRadius: 12,
    color: appTheme.colors.danger,
    marginBottom: 14,
    padding: 11,
  },
  fullBanner: {
    backgroundColor: appTheme.colors.surfaceMuted,
    paddingBottom: 8,
    paddingHorizontal: 24,
    width: '100%',
  },
  handle: {
    alignSelf: 'center',
    backgroundColor: appTheme.colors.border,
    borderRadius: 99,
    height: 6,
    marginBottom: 22,
    marginTop: 12,
    width: 62,
  },
  heroDescription: {
    color: appTheme.colors.textMuted,
    fontSize: 17,
    lineHeight: 25,
    marginTop: 10,
    textAlign: 'center',
  },
  heroTitle: {
    color: appTheme.colors.text,
    fontSize: 25,
    fontWeight: '900',
    letterSpacing: -0.8,
    textAlign: 'center',
  },
  input: {
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: 14,
    borderWidth: 1,
    color: appTheme.colors.text,
    fontSize: 16,
    minHeight: 54,
    paddingHorizontal: 16,
  },
  inputError: { borderColor: appTheme.colors.dangerBorder },
  keyboard: { flex: 1 },
  keyboardArea: { flex: 1, justifyContent: 'flex-end' },
  label: {
    color: appTheme.colors.text,
    fontSize: 14,
    fontWeight: '700',
    marginBottom: 7,
  },
  legalConsent: {
    alignItems: 'flex-start',
    borderColor: appTheme.colors.border,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
    padding: 13,
  },
  legalConsentChecked: {
    backgroundColor: appTheme.colors.accentDark,
    borderColor: appTheme.colors.accentDark,
  },
  legalConsentText: {
    color: appTheme.colors.text,
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
  },
  legalConsentTextChecked: { color: '#FFFFFF' },
  layer: { flex: 1, justifyContent: 'flex-end' },
  logo: { alignSelf: 'center', height: 190, width: '76%' },
  inlineBrandLogo: { height: 28, width: 90 },
  nextButton: {
    backgroundColor: appTheme.colors.surface,
    borderWidth: 0,
    flexBasis: 'auto',
    flexGrow: 0,
    flexShrink: 0,
    height: 72,
    minHeight: 72,
    paddingHorizontal: 18,
    width: '100%',
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  nextContainer: { marginTop: 18, paddingBottom: 4, width: '100%' },
  options: { gap: 13, marginTop: 28, width: '100%' },
  reviewLabel: {
    color: appTheme.colors.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
  reviewRow: {
    alignItems: 'center',
    borderBottomColor: appTheme.colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  reviewText: { flex: 1, paddingRight: 12 },
  reviewValue: { color: appTheme.colors.text, fontSize: 16, marginTop: 3 },
  roleButtons: { flexDirection: 'row', gap: 14, marginTop: 24 },
  roleContent: { paddingBottom: 8, paddingHorizontal: 20 },
  scroll: { flexShrink: 1 },
  scrollContentWithKeyboard: { paddingBottom: 40 },
  scissors: {
    color: appTheme.colors.accentDark,
    fontSize: 29,
    lineHeight: 32,
    marginHorizontal: 20,
    marginTop: -2,
  },
  screen: appStyles.screen,
  section: { flex: 1 },
  separator: { alignItems: 'center', flexDirection: 'row', marginTop: 34 },
  separatorLine: {
    backgroundColor: appTheme.colors.border,
    height: 1,
    width: 88,
  },
  sheet: {
    backgroundColor: appTheme.colors.surfaceMuted,
    borderTopLeftRadius: appTheme.radii.sheet,
    flexShrink: 1,
    borderTopRightRadius: appTheme.radii.sheet,
    overflow: 'hidden',
    ...goldShadow,
  },
  title: {
    color: appTheme.colors.text,
    fontSize: 27,
    fontWeight: '900',
    letterSpacing: -0.7,
  },
  tool: {
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: 150,
    position: 'absolute',
  },
  top: {
    height: 450,
    opacity: 0.46,
    right: -280,
    top: 170,
    transform: [{ rotate: '26deg' }],
    width: 350,
  },
  welcome: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    width: '100%',
  },
  welcomeContent: {
    alignItems: 'center',
    flexGrow: 1,
    paddingBottom: 12,
    paddingHorizontal: 24,
    paddingTop: 34,
  },
  welcomeDescription: {
    color: appTheme.colors.textMuted,
    fontSize: 18,
    lineHeight: 27,
    marginTop: 18,
    textAlign: 'center',
  },
  welcomeMessage: { alignItems: 'center', marginTop: 26 },
  welcomeTitle: {
    color: appTheme.colors.text,
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: -0.8,
  },
});

export const verificationStyles = StyleSheet.create({
  codeInput: {
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: 14,
    borderWidth: 1,
    color: appTheme.colors.text,
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: 10,
    minHeight: 64,
    paddingHorizontal: 18,
    textAlign: 'center',
  },
  countdown: {
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: 12,
    color: appTheme.colors.accentDark,
    fontSize: 15,
    fontWeight: '800',
    marginBottom: 18,
    padding: 12,
    textAlign: 'center',
  },
  countdownExpired: {
    backgroundColor: appTheme.colors.dangerSurface,
    color: appTheme.colors.danger,
  },
  resendButton: { alignItems: 'center', marginTop: 18, paddingVertical: 10 },
  resendText: {
    color: appTheme.colors.accentDark,
    fontSize: 15,
    fontWeight: '800',
  },
});
