import { StyleSheet } from 'react-native';

import { appStyles, appTheme, goldShadow } from '../../components/BottomNavigation';

export const styles = StyleSheet.create({
  appointmentCard: {
    backgroundColor: appTheme.colors.surface,
    borderLeftColor: appTheme.colors.accent,
    borderLeftWidth: 4,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.control,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginBottom: 10,
    padding: 14,
    ...goldShadow,
  },
  appointmentClient: {
    color: appTheme.colors.accentDark,
    fontSize: 15,
    fontWeight: '900',
  },
  appointmentCopy: { flex: 1 },
  appointmentMeta: {
    color: appTheme.colors.textMuted,
    fontSize: 12,
    marginTop: 3,
  },
  appointmentModal: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    bottom: 0,
    left: 0,
    padding: 22,
    position: 'absolute',
    right: 0,
  },
  appointmentModalBackdrop: {
    backgroundColor: appTheme.colors.overlay,
    flex: 1,
  },
  appointmentModalCopy: {
    color: appTheme.colors.textMuted,
    fontSize: 15,
    marginTop: 6,
  },
  confirmationCheck: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    marginTop: 8,
  },
  confirmationCheckText: {
    color: appTheme.colors.text,
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
  },
  modalPayphoneAction: {
    alignItems: 'center',
    backgroundColor: '#287247',
    borderRadius: 14,
    flexDirection: 'row',
    gap: 9,
    justifyContent: 'center',
    marginTop: 12,
    padding: 14,
  },
  paymentDetail: { color: appTheme.colors.text, fontSize: 13, lineHeight: 19 },
  paymentDetails: {
    backgroundColor: appTheme.colors.surfaceMuted,
    borderRadius: 14,
    gap: 6,
    marginTop: 14,
    padding: 14,
  },
  paymentInput: {
    borderColor: appTheme.colors.border,
    borderRadius: 12,
    borderWidth: 1,
    color: appTheme.colors.text,
    fontSize: 15,
    padding: 12,
  },
  paymentNoteInput: { minHeight: 72, textAlignVertical: 'top' },
  paymentSheet: {
    backgroundColor: appTheme.colors.surface,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    gap: 10,
    marginTop: 'auto',
    padding: 22,
    paddingBottom: 36,
  },
  paymentSheetRoot: { backgroundColor: appTheme.colors.overlay, flex: 1 },
  paymentWarning: {
    color: '#7A4300',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 8,
  },
  appointmentModalTitle: {
    color: appTheme.colors.accentDark,
    fontSize: 23,
    fontWeight: '900',
    marginTop: 14,
  },
  publicBookingBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#DDEBFF',
    borderRadius: 999,
    color: '#174A8B',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 7,
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  modalCloseAction: { alignItems: 'center', paddingVertical: 16 },
  modalCloseText: {
    color: appTheme.colors.accentDark,
    fontSize: 15,
    fontWeight: '800',
  },
  modalDangerAction: {
    alignItems: 'center',
    borderColor: '#F4C7C3',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    justifyContent: 'center',
    marginTop: 10,
    paddingVertical: 15,
  },
  modalDangerText: { color: '#B42318', fontSize: 15, fontWeight: '900' },
  modalHandle: {
    alignSelf: 'center',
    backgroundColor: appTheme.colors.accentLight,
    borderRadius: 3,
    height: 5,
    width: 46,
  },
  modalPrimaryAction: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 14,
    flexDirection: 'row',
    gap: 9,
    justifyContent: 'center',
    marginTop: 23,
    paddingVertical: 16,
  },
  modalPrimaryText: { color: '#FFFFFF', fontSize: 15, fontWeight: '900' },
  modalWhatsAppAction: {
    alignItems: 'center',
    backgroundColor: '#EAF6EE',
    borderColor: '#9DCCAC',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginTop: 10,
    minHeight: 54,
  },
  modalWhatsAppText: { color: '#176B3A', fontSize: 15, fontWeight: '900' },
  appointmentTime: {
    color: appTheme.colors.accentDark,
    fontSize: 13,
    fontWeight: '900',
  },
  checkboxLabel: {
    color: appTheme.colors.text,
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
  },
  checkboxRow: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.control,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    marginTop: 12,
    minHeight: 62,
    paddingHorizontal: 15,
  },
  checkboxRowSelected: {
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.accent,
    borderWidth: 2,
  },
  optionTile: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.control,
    borderWidth: 1,
    justifyContent: 'center',
    marginTop: 9,
    minHeight: 88,
    paddingHorizontal: 10,
    width: 116,
  },
  optionTileLabel: {
    color: appTheme.colors.text,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 5,
    textAlign: 'center',
  },
  optionTileLabelSelected: { color: appTheme.colors.text },
  optionTileSelected: {
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.accent,
    borderWidth: 2,
    zIndex: 1,
  },
  settingsBackdrop: {
    backgroundColor: appTheme.colors.overlay,
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  horizontalOptions: { gap: 10, paddingHorizontal: 2, paddingTop: 11 },
  settingsDragArea: { paddingBottom: 8 },
  settingsHandle: {
    alignSelf: 'center',
    backgroundColor: '#C8C9CB',
    borderRadius: 3,
    height: 5,
    width: 46,
  },
  settingsOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  settingsSection: {
    color: appTheme.colors.text,
    fontSize: 16,
    fontWeight: '900',
    marginTop: 25,
  },
  settingsSheet: {
    backgroundColor: appTheme.colors.surface,
    borderTopLeftRadius: appTheme.radii.sheet,
    borderTopRightRadius: appTheme.radii.sheet,
    overflow: 'hidden',
    width: '100%',
  },
  settingsContent: {
    paddingBottom: 20,
    paddingHorizontal: 24,
    paddingTop: 14,
  },
  settingsScroll: {
    backgroundColor: appTheme.colors.surface,
    width: '100%',
  },
  settingsControlPressed: { opacity: 0.86 },
  settingsTitle: {
    color: appTheme.colors.text,
    fontSize: 23,
    fontWeight: '900',
    marginTop: 17,
  },
  availability: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 1,
    gap: 10,
    maxWidth: '58%',
    minWidth: 0,
  },
  availabilityCopy: {
    color: appTheme.colors.textMuted,
    fontSize: 12,
    marginTop: 2,
  },
  availabilityLabel: {
    color: appTheme.colors.accentDark,
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 17,
  },
  availabilityText: { flex: 1, minWidth: 0 },
  availabilityRing: {
    alignItems: 'center',
    borderColor: appTheme.colors.accent,
    borderRadius: 26,
    borderWidth: 4,
    height: 52,
    justifyContent: 'center',
    width: 52,
  },
  date: {
    color: appTheme.colors.textMuted,
    fontSize: 14,
    fontWeight: '600',
    marginTop: 3,
    textTransform: 'capitalize',
  },
  dayButton: {
    alignItems: 'center',
    borderRadius: 18,
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    minHeight: 65,
  },
  dayButtonSelected: {
    backgroundColor: appTheme.colors.surface,
    shadowColor: appTheme.colors.accentDark,
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 10,
  },
  dayName: {
    color: appTheme.colors.textMuted,
    fontSize: 10,
    fontWeight: '800',
  },
  dayNameSelected: { color: appTheme.colors.accentDark },
  dayNumber: {
    color: appTheme.colors.accentDark,
    fontSize: 17,
    fontWeight: '900',
  },
  dayNumberSelected: { color: appTheme.colors.accentDark },
  dayNumberToday: {
    textDecorationLine: 'underline',
    textDecorationStyle: 'solid',
  },
  eyebrow: {
    color: appTheme.colors.accentDark,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  filterButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: 18,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  // El acceso global a notificaciones ocupa el extremo superior derecho.
  // Reservamos ese espacio para que los dos controles de Agenda sigan siendo
  // visibles y táctiles en pantallas angostas.
  headerActions: { flexDirection: 'row', gap: 14, paddingRight: 72 },
  headerCopy: { flex: 1, minWidth: 0, paddingRight: 14 },
  floatingButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 28,
    bottom: 94,
    flexDirection: 'row',
    gap: 7,
    paddingHorizontal: 18,
    paddingVertical: 15,
    position: 'absolute',
    right: 20,
    shadowColor: appTheme.colors.accentDark,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
  },
  floatingLabel: { color: '#ffffff', fontSize: 14, fontWeight: '900' },
  header: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 22,
    paddingTop: 14,
  },
  hour: {
    color: '#7a7a7a',
    fontSize: 12,
    fontWeight: '800',
    paddingTop: 1,
    width: 50,
  },
  inputLabel: {
    color: appTheme.colors.text,
    fontSize: 13,
    fontWeight: '800',
    marginTop: 5,
  },
  hourContent: { flex: 1, minHeight: 89, paddingLeft: 10 },
  hourDivider: {
    borderStyle: 'dashed',
    borderTopColor: appTheme.colors.border,
    borderTopWidth: 1,
    height: 1,
    marginBottom: 9,
  },
  hourRow: { flexDirection: 'row' },
  screen: appStyles.screen,
  summary: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 20,
    marginTop: 16,
    padding: 16,
    ...goldShadow,
  },
  summaryPrimary: { flex: 1, minWidth: 0, paddingRight: 12 },
  summaryLabel: {
    color: appTheme.colors.textMuted,
    fontSize: 13,
    marginTop: 2,
  },
  summaryValue: {
    color: appTheme.colors.accentDark,
    fontSize: 21,
    fontWeight: '900',
  },
  timeline: { marginTop: 13, position: 'relative' },
  timelinePage: { flex: 1 },
  timelineWrapper: { flex: 1, overflow: 'hidden' },
  timelineContent: {
    backgroundColor: appTheme.colors.surface,
    borderTopColor: appTheme.colors.border,
    borderTopWidth: 1,
    marginTop: 12,
    paddingBottom: 132,
    paddingHorizontal: 20,
    paddingTop: 22,
  },
  timelineHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  timelineTitle: {
    color: appTheme.colors.accentDark,
    fontSize: 18,
    fontWeight: '900',
  },
  title: {
    color: appTheme.colors.text,
    fontSize: 33,
    fontWeight: '900',
    letterSpacing: -1,
  },
  viewControl: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: 13,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  viewControls: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 14,
    justifyContent: 'flex-end',
    marginHorizontal: 22,
    marginTop: -36,
  },
  weekPill: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: 13,
    flexDirection: 'row',
    height: 36,
    justifyContent: 'center',
    width: 42,
  },
  calendarClose: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 14,
    marginTop: 18,
    paddingVertical: 13,
  },
  calendarCloseLabel: { color: '#ffffff', fontSize: 14, fontWeight: '900' },
  calendarModal: {
    alignSelf: 'stretch',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 26,
    marginHorizontal: 20,
    padding: 20,
    shadowColor: appTheme.colors.accentDark,
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 22,
  },
  calendarModalBackdrop: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.overlay,
    flex: 1,
    justifyContent: 'center',
  },
  calendarModalHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  calendarMonthLabel: {
    color: appTheme.colors.accentDark,
    fontSize: 18,
    fontWeight: '900',
    textTransform: 'capitalize',
  },
  calendarSection: { marginHorizontal: 20, marginTop: 20 },
  emptySchedule: {
    color: appTheme.colors.textMuted,
    fontSize: 14,
    paddingVertical: 22,
  },
  monthControl: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: 14,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  monthDate: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    width: '14.2857%',
  },
  monthDateLabel: {
    color: appTheme.colors.accentDark,
    fontSize: 14,
    fontWeight: '700',
  },
  monthDateLabelSelected: { color: '#ffffff' },
  monthDateSelected: {
    backgroundColor: appTheme.colors.accent,
    borderRadius: 14,
  },
  monthDateToday: {
    color: appTheme.colors.accentDark,
    textDecorationLine: 'underline',
  },
  monthGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 8 },
  monthWeekday: {
    color: appTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
    width: '14.2857%',
  },
  monthWeekdays: { flexDirection: 'row', marginTop: 22 },
  weekSelector: {
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: 23,
    flexDirection: 'row',
    padding: 6,
  },
});
