import { StyleSheet } from 'react-native';

import {
  appStyles,
  appTheme,
  goldShadow,
} from '../../components/BottomNavigation';

export const styles = StyleSheet.create({
  actions: { flexDirection: 'row', gap: 10, marginTop: 24 },
  balanceAmount: {
    color: '#288B52',
    fontSize: 38,
    fontWeight: '900',
    marginTop: 4,
  },
  balanceCard: {
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: 24,
    borderWidth: 1,
    padding: 22,
    ...goldShadow,
  },
  balanceDivider: { backgroundColor: '#E5E7EB', height: 1, marginVertical: 18 },
  balanceFooter: {
    alignItems: 'flex-end',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  balanceInformation: { flex: 1, paddingRight: 12 },
  balanceLabel: { color: '#303743', fontSize: 16, fontWeight: '800' },
  balanceMeta: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 3,
  },
  balanceMetaLabel: { color: '#737B87', fontSize: 13 },
  baseInfo: { color: '#5D6672', flex: 1, fontSize: 13, lineHeight: 19 },
  baseInfoBox: {
    alignItems: 'flex-start',
    backgroundColor: '#F1F3F5',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 8,
    marginTop: 9,
    padding: 11,
  },
  back: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  backdrop: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  confirm: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 15,
    flex: 1,
    justifyContent: 'center',
    minHeight: 52,
  },
  confirmDisabled: { opacity: 0.45 },
  copy: {
    color: '#6E7785',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 9,
    textAlign: 'center',
  },
  dayAmount: {
    color: '#288B52',
    fontSize: 30,
    fontWeight: '900',
    marginTop: 3,
  },
  dayCard: { backgroundColor: '#F1F4FA', borderRadius: 25, padding: 23 },
  dayCopy: { color: '#59697C', fontSize: 14, lineHeight: 20, marginTop: 14 },
  dayLabel: {
    color: '#59697C',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 22,
  },
  dayTitle: { color: '#111827', fontSize: 19, fontWeight: '900' },
  detailsLink: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '900',
    textDecorationLine: 'underline',
  },
  empty: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    paddingHorizontal: 42,
  },
  exit: {
    alignItems: 'center',
    borderColor: '#C8CDD4',
    borderRadius: 15,
    borderWidth: 1,
    flex: 0.8,
    justifyContent: 'center',
    minHeight: 52,
  },
  exitText: { color: '#111827', fontWeight: '900' },
  floatingSaleButton: {
    borderRadius: 30,
    height: 58,
    right: 24,
    position: 'absolute',
    width: 58,
    zIndex: 1001,
    ...goldShadow,
  },
  floatingSaleButtonContent: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 30,
    flex: 1,
    justifyContent: 'center',
  },
  floatingSaleButtonPressed: { opacity: 0.84, transform: [{ scale: 0.97 }] },
  handle: {
    alignSelf: 'center',
    backgroundColor: '#C8CDD4',
    borderRadius: 3,
    height: 5,
    width: 45,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 18,
  },
  infoButton: {
    alignItems: 'center',
    backgroundColor: '#111827',
    borderRadius: 10,
    height: 20,
    justifyContent: 'center',
    width: 20,
  },
  infoButtonLabel: { color: '#FFFFFF', fontSize: 13, fontWeight: '900' },
  icon: {
    alignItems: 'center',
    backgroundColor: '#E5E7EB',
    borderRadius: 58,
    height: 116,
    justifyContent: 'center',
    width: 116,
  },
  input: {
    backgroundColor: '#F6F7F8',
    borderColor: '#D8DDE3',
    borderRadius: 15,
    borderWidth: 1,
    color: '#111827',
    fontSize: 17,
    marginTop: 9,
    padding: 15,
  },
  inlineEmpty: { color: '#737B87', fontSize: 13, paddingVertical: 8 },
  label: { color: '#111827', fontSize: 14, fontWeight: '800', marginTop: 22 },
  member: {
    borderColor: '#D8DDE3',
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 10,
  },
  memberText: { color: '#111827', fontSize: 14, fontWeight: '800' },
  members: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 10 },
  moneyLabel: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  movementAmount: { fontSize: 14, fontWeight: '900' },
  movementCopy: { flex: 1 },
  movementExpense: { color: '#B54747' },
  movementIcon: {
    alignItems: 'center',
    backgroundColor: '#F3F5F7',
    borderRadius: 15,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  movementIncome: { color: '#288B52' },
  movementMeta: { color: '#737B87', fontSize: 12, marginTop: 2 },
  movementName: { color: '#111827', fontSize: 14, fontWeight: '800' },
  movementRow: {
    alignItems: 'center',
    borderBottomColor: '#E9EBEE',
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 11,
    paddingVertical: 12,
  },
  movementsTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '900',
    marginTop: 8,
  },
  noMovements: {
    color: '#7A828E',
    fontSize: 15,
    paddingVertical: 24,
    textAlign: 'center',
  },
  openContent: { gap: 16, paddingBottom: 105, paddingHorizontal: 24 },
  openScroll: { flex: 1 },
  overlay: {
    backgroundColor: 'rgba(17,24,39,.4)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  primary: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 16,
    flexDirection: 'row',
    gap: 8,
    marginTop: 25,
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  primaryText: { color: '#FFFFFF', fontWeight: '900' },
  screen: appStyles.screen,
  modalKeyboard: { flex: 1 },
  sessionActions: { alignSelf: 'stretch', marginTop: 24 },
  closeButton: { alignItems: 'center', marginTop: 20, padding: 10 },
  closeText: { color: '#9F1D2F', fontWeight: '900' },
  selected: {
    backgroundColor: appTheme.colors.accent,
    borderColor: appTheme.colors.accent,
  },
  selectedText: { color: '#FFFFFF' },
  sheet: {
    backgroundColor: appTheme.colors.surfaceMuted,
    borderTopLeftRadius: appTheme.radii.sheet,
    borderTopRightRadius: appTheme.radii.sheet,
  },
  sheetContent: {
    paddingBottom: 34,
    paddingHorizontal: 22,
    paddingTop: 14,
  },
  sheetTitle: {
    color: '#111827',
    fontSize: 23,
    fontWeight: '900',
    marginTop: 17,
  },
  state: { color: '#111827', fontSize: 24, fontWeight: '900', marginTop: 21 },
  title: { color: '#111827', fontSize: 22, fontWeight: '900' },
});
