import { StyleSheet } from 'react-native';

import { appTheme, goldButtonShadow } from '../../components/BottomNavigation';

export const styles = StyleSheet.create({
  additionalFields: { marginTop: 4 },
  additionalHeading: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '900',
    marginTop: 17,
  },
  additionalLabel: {
    color: '#111827',
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
  },
  additionalTrigger: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 18,
    paddingVertical: 7,
  },
  addLabelButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: appTheme.radii.control,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  activeBadge: {
    alignItems: 'center',
    backgroundColor: '#E5F7ED',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  activeDot: {
    backgroundColor: '#22A861',
    borderRadius: 4,
    height: 7,
    width: 7,
  },
  activeLabel: { color: '#167644', fontSize: 12, fontWeight: '800' },
  avatar: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderColor: appTheme.colors.white,
    borderRadius: 42,
    borderWidth: 4,
    height: 84,
    justifyContent: 'center',
    shadowColor: appTheme.colors.accentDark,
    shadowOpacity: 0.18,
    shadowRadius: 12,
    width: 84,
  },
  avatarText: { color: appTheme.colors.white, fontSize: 29, fontWeight: '900' },
  backButton: {
    backgroundColor: appTheme.colors.accent,
    borderRadius: appTheme.radii.control,
    ...goldButtonShadow,
    marginTop: 18,
    paddingHorizontal: 20,
    paddingVertical: 13,
  },
  backLabel: { color: appTheme.colors.white, fontWeight: '900' },
  backdrop: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  badges: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 10 },
  cancelButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.control,
    borderWidth: 1,
    flex: 1,
    justifyContent: 'center',
    minHeight: 54,
  },
  cancelLabel: {
    color: appTheme.colors.accentDark,
    fontSize: 15,
    fontWeight: '900',
  },
  content: {
    paddingBottom: 42,
    paddingHorizontal: appTheme.spacing.page,
    paddingTop: 22,
  },
  detailsCard: {
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.card,
    borderWidth: 1,
    paddingHorizontal: 16,
    shadowColor: appTheme.colors.accentDark,
    shadowOpacity: 0.035,
    shadowRadius: 9,
  },
  colorLabel: {
    color: appTheme.colors.text,
    fontSize: 14,
    fontWeight: '900',
    marginTop: 20,
  },
  colorList: { flexDirection: 'row', gap: 12, marginTop: 12 },
  colorOption: { borderRadius: 18, height: 36, width: 36 },
  colorOptionSelected: { borderColor: appTheme.colors.accent, borderWidth: 3 },
  emptyLabel: {
    color: appTheme.colors.textMuted,
    fontSize: 13,
    fontWeight: '700',
  },
  labelChip: { borderRadius: 12, paddingHorizontal: 9, paddingVertical: 5 },
  labelChipText: {
    color: appTheme.colors.white,
    fontSize: 12,
    fontWeight: '900',
  },
  labelList: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginTop: 6 },
  labelSheet: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderTopLeftRadius: appTheme.radii.sheet,
    borderTopRightRadius: appTheme.radii.sheet,
    paddingBottom: 36,
    paddingHorizontal: 24,
    paddingTop: 16,
  },
  labelsCopy: { flex: 1 },
  labelsRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 14,
  },
  disabled: { opacity: 0.62 },
  editButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: appTheme.radii.control,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  emptyHistory: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.card,
    borderWidth: 1,
    gap: 10,
    padding: 32,
  },
  field: {
    backgroundColor: appTheme.colors.surfaceMuted,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.control,
    borderWidth: 1,
    color: appTheme.colors.text,
    fontSize: 16,
    marginTop: 12,
    paddingHorizontal: 15,
    paddingVertical: 15,
  },
  frequentBadge: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: 12,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  frequentLabel: {
    color: appTheme.colors.accentDark,
    fontSize: 12,
    fontWeight: '800',
  },
  handle: {
    alignSelf: 'center',
    backgroundColor: appTheme.colors.border,
    borderRadius: 4,
    height: 5,
    marginBottom: 20,
    width: 45,
  },
  header: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.background,
    borderBottomColor: appTheme.colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: appTheme.spacing.page,
    paddingVertical: 13,
  },
  headerActions: { flexDirection: 'row', gap: 8, paddingRight: 64 },
  moreButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.control,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  notesField: { minHeight: 92 },
  optionIcon: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: appTheme.radii.control,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  optionLabel: {
    color: appTheme.colors.text,
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
  },
  optionRow: {
    alignItems: 'center',
    borderBottomColor: appTheme.colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 68,
  },
  optionsOverlay: {
    backgroundColor: appTheme.colors.overlay,
    flex: 1,
    justifyContent: 'flex-end',
  },
  optionsSheet: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderTopLeftRadius: appTheme.radii.sheet,
    borderTopRightRadius: appTheme.radii.sheet,
    paddingBottom: 26,
    paddingHorizontal: 22,
    paddingTop: 13,
  },
  optionsTitle: {
    color: appTheme.colors.text,
    fontSize: 22,
    fontWeight: '900',
    marginBottom: 7,
  },
  deleteOption: { borderBottomWidth: 0, marginTop: 4 },
  deleteOptionIcon: { backgroundColor: '#FDECEA' },
  deleteOptionLabel: {
    color: '#B42318',
    flex: 1,
    fontSize: 16,
    fontWeight: '900',
  },
  headerButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: appTheme.radii.control,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  headerTitle: {
    color: appTheme.colors.text,
    flex: 1,
    fontSize: 17,
    fontWeight: '900',
    marginHorizontal: 10,
  },
  commentStars: { flexDirection: 'row', gap: 5 },
  commentsEmpty: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.card,
    borderWidth: 1,
    gap: 12,
    padding: 32,
  },
  commentsTitle: {
    color: appTheme.colors.text,
    fontSize: 17,
    fontWeight: '900',
  },
  filterChip: {
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.control,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  filterChipActive: {
    backgroundColor: appTheme.colors.accent,
    borderColor: appTheme.colors.accent,
  },
  filterChipText: {
    color: appTheme.colors.accentDark,
    fontSize: 12,
    fontWeight: '800',
  },
  filterChipTextActive: { color: appTheme.colors.white },
  filterList: { gap: 7, paddingRight: 12 },
  historyFilters: { gap: 10, marginBottom: 14 },
  orderButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: appTheme.radii.control,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  orderLabel: {
    color: appTheme.colors.accentDark,
    fontSize: 12,
    fontWeight: '900',
  },
  paidLabel: {
    color: '#167644',
    fontSize: 11,
    fontWeight: '900',
    marginTop: 4,
    textAlign: 'right',
  },
  historyCard: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.card,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 11,
    padding: 13,
  },
  historyCopy: { flex: 1 },
  historyDate: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: 13,
    justifyContent: 'center',
    minHeight: 49,
    width: 48,
  },
  historyDay: {
    color: appTheme.colors.accentDark,
    fontSize: 17,
    fontWeight: '900',
  },
  historyMeta: { color: appTheme.colors.textMuted, fontSize: 12, marginTop: 3 },
  historyMonth: {
    color: appTheme.colors.accentDark,
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  historyService: {
    color: appTheme.colors.text,
    fontSize: 14,
    fontWeight: '900',
  },
  historyList: { gap: 10 },
  infoCopy: { flex: 1 },
  infoIcon: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: appTheme.radii.control,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  infoLabel: {
    color: appTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  infoRow: {
    alignItems: 'center',
    borderBottomColor: appTheme.colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    paddingVertical: 14,
  },
  infoRowLast: { borderBottomWidth: 0 },
  infoValue: {
    color: appTheme.colors.text,
    fontSize: 15,
    fontWeight: '700',
    marginTop: 2,
  },
  loading: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  metric: { alignItems: 'center', flex: 1 },
  metricDate: { color: appTheme.colors.text, fontSize: 13, fontWeight: '900' },
  metricDivider: {
    backgroundColor: appTheme.colors.border,
    height: 35,
    width: 1,
  },
  metricLabel: { color: appTheme.colors.textMuted, fontSize: 11, marginTop: 5 },
  metricValue: { color: appTheme.colors.text, fontSize: 19, fontWeight: '900' },
  metrics: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.card,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 15,
    paddingVertical: 16,
    shadowColor: appTheme.colors.accentDark,
    shadowOpacity: 0.035,
    shadowRadius: 8,
  },
  missing: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  missingTitle: {
    color: appTheme.colors.text,
    fontSize: 20,
    fontWeight: '900',
    marginTop: 12,
  },
  name: {
    color: appTheme.colors.text,
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: -0.3,
  },
  noteCopy: { flex: 1 },
  noteDate: { color: appTheme.colors.textMuted, fontSize: 12, marginTop: 9 },
  noteDragArea: { paddingBottom: 10, paddingTop: 4 },
  noteList: { gap: 10, marginTop: 10 },
  notePhoto: { borderRadius: 14, height: 150, marginTop: 12, width: '100%' },
  notePhotoActions: { flexDirection: 'row', gap: 10, marginTop: 16 },
  notePreview: { borderRadius: 16, height: 180, marginTop: 14, width: '100%' },
  noteSaveButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: appTheme.radii.control,
    ...goldButtonShadow,
    marginTop: 20,
    minHeight: 54,
    justifyContent: 'center',
  },
  noteSheet: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderTopLeftRadius: appTheme.radii.sheet,
    borderTopRightRadius: appTheme.radii.sheet,
    paddingBottom: 34,
    paddingHorizontal: 22,
    paddingTop: 10,
  },
  notesHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  photoAction: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accentWash,
    borderRadius: appTheme.radii.control,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 50,
  },
  photoActionLabel: {
    color: appTheme.colors.accentDark,
    fontSize: 13,
    fontWeight: '900',
  },
  notesCard: {
    alignItems: 'flex-start',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.card,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    padding: 18,
  },
  notesText: {
    color: appTheme.colors.text,
    flex: 1,
    fontSize: 15,
    lineHeight: 22,
  },
  overlay: {
    backgroundColor: appTheme.colors.overlay,
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalKeyboard: { flex: 1 },
  phone: { color: appTheme.colors.textMuted, fontSize: 14, marginTop: 4 },
  profileCard: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accentWash,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.card,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 15,
    padding: 17,
  },
  profileCopy: { flex: 1 },
  quickAction: { alignItems: 'center', flex: 1, gap: 7 },
  quickActions: { flexDirection: 'row', justifyContent: 'space-between' },
  quickIcon: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.control,
    borderWidth: 1,
    height: 54,
    justifyContent: 'center',
    width: 54,
  },
  quickLabel: { color: appTheme.colors.text, fontSize: 12, fontWeight: '800' },
  saveButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: appTheme.radii.control,
    flex: 1.15,
    justifyContent: 'center',
    minHeight: 54,
    ...goldButtonShadow,
  },
  saveLabel: { color: appTheme.colors.white, fontSize: 15, fontWeight: '900' },
  screen: { backgroundColor: appTheme.colors.background, flex: 1 },
  secondary: { color: appTheme.colors.textMuted },
  sectionTitle: {
    color: appTheme.colors.text,
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 14,
    marginTop: 27,
  },
  sheet: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderTopLeftRadius: appTheme.radii.sheet,
    borderTopRightRadius: appTheme.radii.sheet,
    paddingBottom: 28,
    paddingHorizontal: 22,
    paddingTop: 13,
  },
  sheetContent: { paddingBottom: 28 },
  sheetActions: { flexDirection: 'row', gap: 10, marginTop: 22 },
  sheetCopy: { color: appTheme.colors.textMuted, fontSize: 14, marginTop: 6 },
  sheetTitle: { color: appTheme.colors.text, fontSize: 22, fontWeight: '900' },
  status: {
    backgroundColor: '#FFF3DE',
    borderRadius: 9,
    color: '#A15C00',
    fontSize: 10,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 4,
  },
  statusCompleted: { backgroundColor: '#E5F7ED', color: '#167644' },
  tab: { alignItems: 'center', flex: 1, paddingBottom: 11, paddingTop: 4 },
  tabActive: {
    borderBottomColor: appTheme.colors.accent,
    borderBottomWidth: 2.5,
  },
  tabLabel: {
    color: appTheme.colors.textMuted,
    fontSize: 13,
    fontWeight: '800',
  },
  tabLabelActive: { color: appTheme.colors.accentDark },
  tabs: {
    borderBottomColor: appTheme.colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    marginBottom: 16,
    marginTop: 31,
  },
});
