import { StyleSheet } from 'react-native';

import { appStyles, appTheme, goldShadow } from '../../components/BottomNavigation';

export const styles = StyleSheet.create({
  additionalFields: { marginTop: 5 },
  additionalHeading: {
    color: '#101c2d',
    fontSize: 14,
    fontWeight: '900',
    marginTop: 14,
  },
  additionalLabel: {
    color: '#101c2d',
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
  },
  additionalTrigger: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 18,
    paddingVertical: 7,
  },
  backdrop: { bottom: 0, left: 0, position: 'absolute', right: 0, top: 0 },
  addButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 19,
    height: 58,
    justifyContent: 'center',
    shadowColor: appTheme.colors.accentDark,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 13,
    width: 58,
  },
  floatingAdd: {
    bottom: 96,
    position: 'absolute',
    right: 24,
    zIndex: 2,
  },
  floatingAddContent: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 19,
    height: 58,
    justifyContent: 'center',
    shadowColor: appTheme.colors.accentDark,
    shadowOffset: { height: 8, width: 0 },
    shadowOpacity: 0.22,
    shadowRadius: 13,
    width: 58,
    zIndex: 2,
  },
  headerSpacer: { height: 50, width: 50 },
  avatar: {
    alignItems: 'center',
    backgroundColor: '#e2e4e7',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  avatarLabel: { color: '#101c2d', fontSize: 17, fontWeight: '900' },
  clientCopy: { flex: 1 },
  clientLabel: { borderRadius: 9, paddingHorizontal: 7, paddingVertical: 3 },
  clientLabelText: { color: '#ffffff', fontSize: 10, fontWeight: '900' },
  clientLabels: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
    marginTop: 7,
  },
  clientName: { color: '#101c2d', fontSize: 16, fontWeight: '900' },
  clientPhone: { color: '#69717d', fontSize: 13, marginTop: 3 },
  clientRow: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    marginBottom: 10,
    padding: 14,
    ...goldShadow,
  },
  clientRowSelected: {
    backgroundColor: '#FFF7E5',
    borderColor: appTheme.colors.accent,
    borderWidth: 2,
  },
  content: { paddingBottom: 128, paddingHorizontal: 24, paddingTop: 28 },
  deletionProgress: {
    backgroundColor: '#FFF7E5',
    borderColor: '#E3B553',
    borderRadius: 16,
    borderWidth: 1,
    marginHorizontal: 24,
    marginTop: 12,
    padding: 14,
  },
  deletionProgressCopy: {
    color: '#5D6672',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 8,
  },
  deletionProgressFill: {
    backgroundColor: appTheme.colors.accent,
    borderRadius: 4,
    height: '100%',
  },
  deletionProgressHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  deletionProgressLabel: { color: '#101C2D', fontSize: 14, fontWeight: '900' },
  deletionProgressTrack: {
    backgroundColor: '#E7DDC9',
    borderRadius: 4,
    height: 8,
    marginTop: 10,
    overflow: 'hidden',
  },
  deletionProgressValue: { color: '#8D620C', fontSize: 14, fontWeight: '900' },
  disabled: { opacity: 0.55 },
  dialogAction: {
    alignItems: 'center',
    borderRadius: 15,
    flex: 1,
    justifyContent: 'center',
    minHeight: 48,
    paddingHorizontal: 12,
  },
  dialogActionDefault: { backgroundColor: '#F2F3F4' },
  dialogActionDestructive: { backgroundColor: '#B42318' },
  dialogActionPrimary: { backgroundColor: appTheme.colors.accent },
  dialogActionLabel: { fontSize: 14, fontWeight: '900' },
  dialogActionLabelDefault: { color: '#101C2D' },
  dialogActionLabelOnAccent: { color: '#FFFFFF' },
  dialogActions: { flexDirection: 'row', gap: 10, marginTop: 24 },
  dialogBackdrop: {
    backgroundColor: 'rgba(16, 28, 45, 0.52)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  dialogCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E1DA',
    borderRadius: 26,
    borderWidth: 1,
    marginHorizontal: 24,
    maxWidth: 420,
    padding: 22,
    width: '88%',
    zIndex: 1,
  },
  dialogIcon: {
    alignItems: 'center',
    backgroundColor: '#FFF1CC',
    borderRadius: 18,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  dialogMessage: {
    color: '#5D6672',
    fontSize: 14,
    lineHeight: 21,
    marginTop: 9,
  },
  dialogOverlay: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  dialogTitle: {
    color: '#101C2D',
    fontSize: 21,
    fontWeight: '900',
    marginTop: 16,
  },
  empty: { alignItems: 'center', marginHorizontal: 20, marginTop: 76 },
  emptyAction: {
    color: '#101c2d',
    fontSize: 16,
    fontWeight: '900',
    marginTop: 24,
  },
  emptyCopy: {
    color: '#5d6672',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 10,
    textAlign: 'center',
  },
  emptyIcon: {
    alignItems: 'center',
    backgroundColor: '#e4e7eb',
    borderRadius: 72,
    height: 144,
    justifyContent: 'center',
    width: 144,
  },
  emptyTitle: {
    color: '#101c2d',
    fontSize: 22,
    fontWeight: '900',
    marginTop: 21,
  },
  filterChip: {
    borderRadius: 16,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 7,
  },
  filterChipText: { color: '#101c2d', fontSize: 13, fontWeight: '800' },
  filterChipTextActive: { color: '#ffffff' },
  filterList: { gap: 8, paddingRight: 24 },
  filterSection: { marginTop: 18 },
  filterTitle: {
    color: '#5d6672',
    fontSize: 13,
    fontWeight: '800',
    marginBottom: 9,
  },
  field: {
    backgroundColor: '#f2f3f4',
    borderColor: '#d8dadd',
    borderRadius: 16,
    borderWidth: 1,
    color: '#101c2d',
    fontSize: 16,
    marginTop: 12,
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  handle: {
    alignSelf: 'center',
    backgroundColor: '#c5c8cd',
    borderRadius: 3,
    height: 5,
    width: 46,
  },
  header: {
    alignItems: 'center',
    borderBottomColor: '#e4e5e7',
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 24,
    paddingVertical: 16,
  },
  headerTitle: { color: '#101c2d', fontSize: 22, fontWeight: '900' },
  importActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
  importBackdrop: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  importCancelButton: {
    alignItems: 'center',
    backgroundColor: '#F2F3F4',
    borderRadius: 15,
    flex: 0.8,
    justifyContent: 'center',
    minHeight: 50,
  },
  importCancelLabel: { color: '#101C2D', fontSize: 14, fontWeight: '900' },
  importConfirmButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 15,
    flex: 1.2,
    justifyContent: 'center',
    minHeight: 50,
  },
  importConfirmLabel: { color: '#FFFFFF', fontSize: 14, fontWeight: '900' },
  importContactAvatar: {
    alignItems: 'center',
    backgroundColor: '#E8EAED',
    borderRadius: 19,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  importContactAvatarLabel: {
    color: '#101C2D',
    fontSize: 15,
    fontWeight: '900',
  },
  importContactCopy: { flex: 1 },
  importContactName: { color: '#101C2D', fontSize: 14, fontWeight: '900' },
  importContactPhone: { color: '#69717D', fontSize: 12, marginTop: 2 },
  importContactRow: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4E5E7',
    borderRadius: 15,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 11,
  },
  importContactRowSelected: {
    backgroundColor: '#FFF7E5',
    borderColor: '#C79532',
  },
  importCopy: { color: '#5D6672', fontSize: 14, lineHeight: 20, marginTop: 7 },
  importEmpty: {
    color: '#69717D',
    fontSize: 14,
    fontWeight: '700',
    paddingVertical: 28,
    textAlign: 'center',
  },
  importList: { gap: 8, paddingBottom: 4 },
  importListScroll: { marginTop: 5, maxHeight: 340 },
  importOverlay: {
    backgroundColor: 'rgba(16, 28, 45, 0.48)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  importSearchBox: {
    alignItems: 'center',
    backgroundColor: '#F2F3F4',
    borderColor: '#E4E5E7',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginTop: 16,
    paddingHorizontal: 12,
  },
  importSearchInput: {
    color: '#101C2D',
    flex: 1,
    fontSize: 14,
    paddingVertical: 13,
  },
  importSelectAll: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    paddingVertical: 11,
  },
  importSelectAllCount: {
    backgroundColor: '#E8EAED',
    borderRadius: 10,
    color: '#5D6672',
    fontSize: 11,
    fontWeight: '900',
    minWidth: 22,
    paddingHorizontal: 6,
    paddingVertical: 3,
    textAlign: 'center',
  },
  importSelectAllLabel: { color: '#101C2D', fontSize: 13, fontWeight: '900' },
  importSheet: {
    backgroundColor: appTheme.colors.surfaceMuted,
    borderTopLeftRadius: appTheme.radii.sheet,
    borderTopRightRadius: appTheme.radii.sheet,
    elevation: 2,
    maxHeight: '88%',
    paddingBottom: 26,
    paddingHorizontal: 24,
    zIndex: 1,
  },
  importTitle: {
    color: '#101C2D',
    fontSize: 23,
    fontWeight: '900',
    marginTop: 10,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 18,
    height: 50,
    justifyContent: 'center',
    marginRight: 64,
    width: 50,
  },
  selectionAction: {
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderRadius: 16,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  selectionActions: { flexDirection: 'row', gap: 8 },
  list: { marginTop: 23 },
  overlay: {
    backgroundColor: 'rgba(16, 28, 45, 0.48)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalKeyboard: { flex: 1 },
  saveButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 17,
    marginTop: 22,
    paddingVertical: 17,
  },
  saveButtonDisabled: { opacity: 0.45 },
  saveLabel: { color: '#ffffff', fontSize: 16, fontWeight: '900' },
  screen: appStyles.screen,
  searchBox: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.border,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    marginTop: 28,
    paddingHorizontal: 17,
    height: 67,
    ...goldShadow,
  },
  searchInput: { color: '#101c2d', flex: 1, fontSize: 16 },
  selectAllButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
    paddingHorizontal: 2,
    paddingVertical: 7,
  },
  selectAllCount: {
    backgroundColor: '#E8EAED',
    borderRadius: 11,
    color: '#5D6672',
    fontSize: 12,
    fontWeight: '900',
    marginLeft: 2,
    minWidth: 23,
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 3,
    textAlign: 'center',
  },
  selectAllLabel: { color: '#101C2D', fontSize: 14, fontWeight: '900' },
  sheet: {
    backgroundColor: appTheme.colors.surfaceMuted,
    borderTopLeftRadius: appTheme.radii.sheet,
    borderTopRightRadius: appTheme.radii.sheet,
    paddingHorizontal: 24,
    paddingBottom: 38,
  },
  sheetDragArea: { paddingTop: 16, paddingBottom: 4 },
  sheetCopy: { color: '#5d6672', fontSize: 15, lineHeight: 21, marginTop: 8 },
  sheetTitle: {
    color: '#101c2d',
    fontSize: 24,
    fontWeight: '900',
    marginTop: 18,
  },
  step: {
    color: '#101c2d',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1.2,
  },
  subtitle: { color: '#5d6672', fontSize: 16, lineHeight: 23, marginTop: 9 },
  title: {
    color: appTheme.colors.text,
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: -0.8,
    marginTop: 9,
  },
});
