import { Platform, StyleSheet } from 'react-native';

import {
  appStyles,
  appTheme,
  goldButtonShadow,
} from '../../components/BottomNavigation';

export const styles = StyleSheet.create({
  addQuickAction: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(199, 149, 50, 0.28)',
    borderRadius: 17,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 48,
    paddingHorizontal: 14,
    ...goldButtonShadow,
  },
  addQuickActionIcon: {
    alignItems: 'center',
    backgroundColor: '#B47D17',
    borderRadius: 11,
    height: 22,
    justifyContent: 'center',
    width: 22,
  },
  addQuickActionLabel: {
    color: '#B47D17',
    fontSize: 13,
    fontWeight: '800',
  },
  addQuickActionRow: { alignItems: 'center', marginTop: 14 },
  businessName: {
    color: '#111111',
    fontSize: 35,
    fontWeight: '900',
    letterSpacing: -1.2,
    marginTop: 2,
  },
  cardCopy: { color: '#000000', fontSize: 15, lineHeight: 22, marginTop: 12 },
  cardHeading: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  cardTitle: {
    color: '#1C1C1C',
    fontSize: 25,
    fontWeight: '900',
    letterSpacing: -0.4,
  },

  content: { paddingBottom: 126, paddingHorizontal: 24, paddingTop: 17 },
  greeting: { color: '#555555', fontSize: 17, lineHeight: 24 },
  linkBox: {
    alignItems: 'center',
    backgroundColor: '#FAF9F6',
    borderRadius: 17,
    flexDirection: 'row',
    gap: 12,
    marginTop: 18,
    minHeight: 72,
    padding: 11,
  },
  linkCopy: { flex: 1 },
  linkLabel: { color: '#000000', fontSize: 12, marginBottom: 5 },
  linkValue: {
    color: '#1C1C1C',
    fontSize: 14,
    fontWeight: '800',
    lineHeight: 19,
  },
  locationActions: { flexDirection: 'row', gap: 12, marginTop: 20 },
  locationBackdrop: {
    backgroundColor: 'rgba(16, 28, 45, 0.58)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  locationBuildingFour: {
    backgroundColor: '#cfd1d4',
    borderRadius: 5,
    bottom: 12,
    height: 29,
    position: 'absolute',
    right: 18,
    width: 51,
  },
  locationBuildingOne: {
    backgroundColor: '#d6d8dc',
    borderRadius: 5,
    height: 42,
    left: 23,
    position: 'absolute',
    top: 17,
    width: 62,
  },
  locationBuildingThree: {
    backgroundColor: '#c7cacf',
    borderRadius: 5,
    height: 44,
    left: 28,
    position: 'absolute',
    top: 87,
    width: 74,
  },
  locationBuildingTwo: {
    backgroundColor: '#c2c5ca',
    borderRadius: 5,
    height: 35,
    position: 'absolute',
    right: 27,
    top: 26,
    width: 76,
  },
  locationButtonDisabled: { opacity: 0.65 },
  locationDescription: {
    color: '#555a63',
    fontSize: 15,
    lineHeight: 22,
    marginTop: 12,
  },
  locationError: {
    color: '#b42318',
    fontSize: 13,
    fontWeight: '700',
    marginTop: 13,
    textAlign: 'center',
  },
  locationHandle: {
    alignSelf: 'center',
    backgroundColor: '#a4a7ad',
    borderRadius: 4,
    height: 5,
    marginBottom: 22,
    width: 46,
  },
  locationInput: {
    color: '#101c2d',
    flex: 1,
    fontSize: 15,
    fontWeight: '700',
    marginLeft: 10,
    paddingBottom: 8,
    paddingTop: 8,
  },
  locationInputLabel: {
    backgroundColor: '#f4f4f3',
    color: '#555a63',
    fontSize: 12,
    left: 13,
    paddingHorizontal: 4,
    position: 'absolute',
    top: -8,
    zIndex: 1,
  },
  locationInputWrap: {
    alignItems: 'center',
    borderRadius: 16,
    flexDirection: 'row',
    marginTop: 24,
    minHeight: 58,
    paddingHorizontal: 15,
  },
  locationMap: {
    backgroundColor: '#e9eaec',
    borderRadius: 20,
    height: 145,
    marginTop: 18,
    overflow: 'hidden',
    position: 'relative',
  },
  locationMapHint: {
    color: '#555a63',
    fontSize: 13,
    marginTop: 9,
    textAlign: 'center',
  },
  locationMarker: {
    alignItems: 'center',
    backgroundColor: '#1c1f24',
    borderRadius: 18,
    elevation: 4,
    height: 36,
    justifyContent: 'center',
    position: 'absolute',
    shadowColor: '#B47D17',
    shadowOpacity: 0.24,
    shadowRadius: 5,
    width: 36,
  },
  locationOverlay: { flex: 1, justifyContent: 'flex-end' },
  locationKeyboardArea: { flex: 1, justifyContent: 'flex-end' },
  locationPrimaryButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 28,
    borderWidth: 0,
    flex: 1.25,
    justifyContent: 'center',
    minHeight: 56,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  locationPrimaryLabel: {
    color: appTheme.colors.accentDark,
    fontSize: 15,
    fontWeight: '900',
  },
  locationRoad: {
    backgroundColor: '#f9f9f8',
    position: 'absolute',
  },
  locationRoadOne: {
    height: 21,
    left: -8,
    right: -8,
    top: 67,
    transform: [{ rotate: '-9deg' }],
  },
  locationRoadTwo: {
    bottom: -12,
    top: -12,
    transform: [{ rotate: '27deg' }],
    width: 19,
    left: '52%',
  },
  locationSecondaryButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 28,
    borderWidth: 0,
    flex: 0.75,
    justifyContent: 'center',
    minHeight: 56,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  locationSecondaryLabel: {
    color: appTheme.colors.accentDark,
    fontSize: 15,
    fontWeight: '900',
  },
  locationSheet: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    elevation: 14,
    paddingHorizontal: 24,
    paddingTop: 14,
    shadowColor: '#B47D17',
    shadowOpacity: 0.16,
    shadowRadius: 14,
  },
  locationSuccess: {
    color: '#277a48',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 13,
    textAlign: 'center',
  },
  locationTitle: {
    color: '#101c2d',
    fontSize: 25,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  permissionActions: { flexDirection: 'row', gap: 12, marginTop: 30 },
  permissionBackdrop: {
    backgroundColor: 'rgba(16, 28, 45, 0.58)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  permissionDescription: {
    color: '#555a63',
    fontSize: 16,
    lineHeight: 24,
    marginTop: 13,
    textAlign: 'center',
  },
  permissionHandle: {
    alignSelf: 'center',
    backgroundColor: '#a4a7ad',
    borderRadius: 4,
    height: 5,
    marginBottom: 24,
    width: 46,
  },
  permissionOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  permissionPrimaryButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 28,
    borderWidth: 0,
    flex: 1,
    justifyContent: 'center',
    minHeight: 56,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  permissionPrimaryLabel: {
    color: appTheme.colors.accentDark,
    fontSize: 16,
    fontWeight: '900',
  },
  permissionSecondaryButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 28,
    borderWidth: 0,
    flex: 1,
    justifyContent: 'center',
    minHeight: 56,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  permissionSecondaryLabel: {
    color: '#B47D17',
    fontSize: 16,
    fontWeight: '900',
  },
  permissionSheet: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    paddingHorizontal: 24,
    paddingTop: 14,
  },
  permissionTitle: {
    color: '#101c2d',
    fontSize: 25,
    fontWeight: '900',
    letterSpacing: -0.4,
    textAlign: 'center',
  },
  openButton: {
    alignItems: 'center',
    backgroundColor: '#C79532',
    borderBottomColor: 'rgba(255, 244, 214, 0.42)',
    borderBottomWidth: 1,
    borderLeftColor: 'rgba(255, 244, 214, 0.42)',
    borderLeftWidth: 1,
    borderRadius: 15,
    borderRightColor: 'rgba(255, 244, 214, 0.42)',
    borderRightWidth: 1,
    borderTopColor: 'rgba(255, 244, 214, 0.42)',
    borderTopWidth: 1,
    elevation: 4,
    ...Platform.select({
      web: {
        experimental_backgroundImage:
          'linear-gradient(135deg, #C79532 0%, #E1B85B 50%, #B47D17 100%)',
      },
    }),
    justifyContent: 'center',
    minHeight: 51,
    overflow: 'visible',
    paddingHorizontal: 19,
    shadowColor: '#B47D17',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 8,
  },
  openButtonFlareTrack: {
    alignItems: 'center',
    bottom: 1,
    height: 1,
    left: 10,
    position: 'absolute',
    right: 10,
    zIndex: 2,
  },
  openButtonFlare: {
    bottom: -8,
    height: 17,
    position: 'absolute',
    width: 17,
  },
  openButtonFlareAura: {
    height: 31,
    left: -7,
    position: 'absolute',
    top: -7,
    width: 31,
  },
  openButtonInnerBorder: {
    borderColor: 'rgba(255, 255, 255, 0.58)',
    borderRadius: 13,
    borderWidth: 1,
    bottom: 1,
    left: 1,
    position: 'absolute',
    right: 1,
    top: 1,
    zIndex: 1,
  },
  openLabel: { color: '#ffffff', fontSize: 16, fontWeight: '900' },
  qrBadge: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 25,
    elevation: 4,
    height: 58,
    justifyContent: 'center',
    shadowColor: '#B47D17',
    shadowOffset: { height: 5, width: 0 },
    shadowOpacity: 0.13,
    shadowRadius: 9,
    width: 58,
  },
  qrSparkle: {
    backgroundColor: '#E1B85B',
    borderRadius: 5,
    height: 7,
    position: 'absolute',
    right: 1,
    top: 8,
    width: 7,
  },
  quickAction: {
    alignItems: 'center',
    flex: 1,
    gap: 5,
    justifyContent: 'center',
    paddingHorizontal: 3,
  },
  quickActions: {
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'space-between',
    marginTop: 22,
  },
  operationAction: { color: '#9A6A17', fontSize: 12, fontWeight: '900' },
  operationActionRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    marginTop: 7,
  },
  operationCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: 'rgba(199, 149, 50, 0.16)',
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 96,
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  operationCardAlert: {
    backgroundColor: '#FFF9EE',
    borderColor: 'rgba(204, 142, 35, 0.28)',
  },
  operationCopy: { flex: 1, minWidth: 0 },
  operationDescription: { color: '#69717D', fontSize: 13, marginTop: 3 },
  operationIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(235, 216, 170, 0.42)',
    borderRadius: 16,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  operationIconAlert: { backgroundColor: 'rgba(244, 194, 97, 0.25)' },
  operationTitle: { color: '#1C1C1C', fontSize: 15, fontWeight: '900' },
  operationsCaption: { color: '#69717D', fontSize: 13, marginTop: 3 },
  operationsHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  operationsList: { gap: 10, marginTop: 13 },
  operationsSection: { marginTop: 28 },
  operationsTitle: { color: '#1C1C1C', fontSize: 21, fontWeight: '900' },
  extraQuickActionRemove: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderColor: '#E6C1BE',
    borderRadius: 14,
    borderWidth: 1,
    height: 28,
    justifyContent: 'center',
    position: 'absolute',
    right: 3,
    top: -3,
    width: 28,
    zIndex: 2,
  },
  extraQuickActionSlot: { position: 'relative', width: '25%' },
  extraQuickActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 16,
    rowGap: 14,
  },
  quickActionsPicker: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderRadius: 28,
    marginHorizontal: 24,
    paddingBottom: 20,
    paddingHorizontal: 18,
    paddingTop: 12,
  },
  quickActionsPickerBackdrop: {
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  quickActionsPickerCopy: {
    color: '#555A63',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 6,
    textAlign: 'center',
  },
  quickActionsPickerEmpty: {
    color: '#555A63',
    fontSize: 14,
    paddingVertical: 18,
    textAlign: 'center',
  },
  quickActionsPickerHandle: {
    alignSelf: 'center',
    backgroundColor: '#C8C9CB',
    borderRadius: 4,
    height: 5,
    width: 42,
  },
  quickActionsPickerIcon: {
    alignItems: 'center',
    backgroundColor: 'rgba(235, 216, 170, 0.34)',
    borderRadius: 16,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  quickActionsPickerLabel: {
    color: '#1C1C1C',
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
  },
  quickActionsPickerList: { marginTop: 17 },
  quickActionsPickerOption: {
    alignItems: 'center',
    borderTopColor: 'rgba(228, 225, 218, 0.8)',
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 62,
  },
  quickActionsPickerOverlay: {
    backgroundColor: 'rgba(16, 28, 45, 0.38)',
    flex: 1,
    justifyContent: 'center',
  },
  quickActionsPickerTitle: {
    color: '#1C1C1C',
    fontSize: 20,
    fontWeight: '900',
    marginTop: 15,
    textAlign: 'center',
  },
  quickIcon: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    elevation: 3,
    height: 44,
    justifyContent: 'center',
    overflow: 'hidden',
    shadowColor: '#B47D17',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 9,
    width: 54,
  },
  quickIconShimmer: {
    backgroundColor: 'rgba(255, 255, 255, 0.72)',
    bottom: -20,
    left: 21,
    position: 'absolute',
    shadowColor: '#B47D17',
    shadowOpacity: 0.8,
    shadowRadius: 8,
    top: -20,
    width: 13,
  },
  quickLabel: {
    color: '#1C1C1C',
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  subscriptionNoticeCard: {
    backgroundColor: appTheme.colors.surface,
    borderColor: appTheme.colors.accentLight,
    borderRadius: appTheme.radii.card,
    borderWidth: 1,
    marginTop: 24,
    overflow: 'hidden',
    padding: 22,
    ...goldButtonShadow,
  },
  subscriptionNoticeCopyColumn: {
    alignItems: 'center',
    gap: 10,
    paddingTop: 6,
  },
  subscriptionNoticeImageColumn: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  subscriptionCrown: {
    height: 112,
    width: 180,
  },
  subscriptionUpgradeButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: appTheme.radii.control,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 18,
    minHeight: 46,
    paddingHorizontal: 16,
    ...goldButtonShadow,
  },
  subscriptionUpgradeLabel: {
    color: appTheme.colors.white,
    fontSize: 14,
    fontWeight: '900',
  },
  reservationCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    elevation: 3,
    marginTop: 24,
    padding: 22,
    shadowColor: '#B47D17',
    shadowOffset: { height: 6, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
  },
  reservationChair: {
    height: 220,
    width: '128%',
  },
  reservationCopyColumn: {
    flex: 1,
    paddingVertical: 8,
  },
  reservationLinkBox: {
    alignItems: 'stretch',
    flexDirection: 'column',
    gap: 8,
    marginTop: 16,
    minHeight: 0,
    padding: 10,
  },
  reservationImageColumn: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
  },
  reservationOpenButton: {
    alignSelf: 'stretch',
    minHeight: 44,
    paddingHorizontal: 14,
  },
  reservationTopRow: {
    alignItems: 'stretch',
    flexDirection: 'row',
  },
  salesCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 30,
    minHeight: 202,
    marginTop: 48,
    overflow: 'hidden',
    padding: 21,
    position: 'relative',
    elevation: 4,
    shadowColor: '#B47D17',
    shadowOffset: { height: 7, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 15,
  },
  salesHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'relative',
    zIndex: 1,
  },
  salesMeta: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 14,
    position: 'relative',
    zIndex: 1,
  },
  salesMetaText: { color: '#000000', fontSize: 15 },
  salesPlanLabel: {
    color: '#555555',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 3,
  },
  salesTitle: { color: '#1C1C1C', fontSize: 18, fontWeight: '600' },
  salesTitleColumn: { flex: 1, minWidth: 0, paddingRight: 12 },
  screen: appStyles.screen,
  summaryButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.88)',
    borderRadius: 22,
    flexDirection: 'row',
    flexShrink: 0,
    gap: 7,
    minHeight: 48,
    paddingHorizontal: 15,
    shadowColor: '#B47D17',
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  summaryLabel: { color: '#B47D17', fontSize: 16, fontWeight: '800' },
  topRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  topCopy: { flex: 1, minWidth: 0, paddingRight: 64 },
  welcome: { alignItems: 'center', marginTop: 52 },
  welcomeCopy: {
    color: '#555a63',
    fontSize: 19,
    marginTop: 10,
    textAlign: 'center',
  },
  welcomeTitle: {
    color: '#101c2d',
    fontSize: 30,
    fontWeight: '900',
    letterSpacing: -0.8,
  },
  welcomeSurveyBackdrop: {
    backgroundColor: 'rgba(16, 28, 45, 0.58)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  welcomeSurveyCheckbox: {
    alignItems: 'center',
    borderRadius: 9,
    height: 24,
    justifyContent: 'center',
    marginRight: 13,
    width: 24,
  },
  welcomeSurveyCheckboxSelected: {
    backgroundColor: '#1c1f24',
  },
  welcomeSurveyError: {
    color: '#b42318',
    fontSize: 14,
    fontWeight: '700',
    marginTop: 14,
    textAlign: 'center',
  },
  welcomeSurveyHand: {
    alignItems: 'center',
    backgroundColor: '#e1e2e4',
    borderRadius: 14,
    height: 48,
    justifyContent: 'center',
    width: 48,
  },
  welcomeSurveyHandle: {
    alignSelf: 'center',
    backgroundColor: '#a4a7ad',
    borderRadius: 4,
    height: 5,
    marginBottom: 22,
    width: 46,
  },
  welcomeSurveyHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 13,
  },
  welcomeSurveyIntro: {
    color: '#555a63',
    fontSize: 16,
    lineHeight: 23,
    marginTop: 16,
  },
  welcomeSurveyOption: {
    alignItems: 'center',
    borderRadius: 16,
    flexDirection: 'row',
    minHeight: 53,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  welcomeSurveyOptionLabel: {
    color: '#101c2d',
    flex: 1,
    fontSize: 14,
    fontWeight: '700',
    lineHeight: 19,
  },
  welcomeSurveyOptionSelected: {
    backgroundColor: '#e8e9eb',
  },
  welcomeSurveyOptions: { gap: 9, marginTop: 18 },
  welcomeSurveyOverlay: { flex: 1, justifyContent: 'flex-end' },
  welcomeSurveyQuestion: {
    color: '#101c2d',
    fontSize: 17,
    fontWeight: '900',
    lineHeight: 24,
    marginTop: 22,
  },
  welcomeSurveySheet: {
    backgroundColor: appTheme.colors.surfaceElevated,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    elevation: 14,
    paddingHorizontal: 24,
    paddingTop: 14,
    shadowColor: '#B47D17',
    shadowOpacity: 0.16,
    shadowRadius: 14,
  },
  welcomeSurveySubmit: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 28,
    borderWidth: 0,
    justifyContent: 'center',
    marginTop: 22,
    minHeight: 56,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  welcomeSurveySubmitDisabled: { opacity: 0.65 },
  welcomeSurveySubmitLabel: {
    color: appTheme.colors.accentDark,
    fontSize: 16,
    fontWeight: '900',
  },
  welcomeSurveySuccess: {
    color: '#277a48',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 14,
    textAlign: 'center',
  },
  welcomeSurveyTitle: {
    color: '#101c2d',
    fontSize: 25,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
});
