import { StyleSheet } from 'react-native';

import { appTheme, goldButtonShadow } from '../../components/BottomNavigation';

export const styles = StyleSheet.create({
  backdrop: StyleSheet.absoluteFill,
  cancelButton: {
    alignItems: 'center',
    borderColor: '#D7DBE0',
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    paddingVertical: 15,
  },
  cancelText: { color: '#46505C', fontSize: 15, fontWeight: '800' },
  chip: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E3D7BF',
    borderRadius: 99,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 9,
  },
  chipActive: { backgroundColor: '#805E21', borderColor: '#805E21' },
  chipText: { color: '#805E21', fontSize: 13, fontWeight: '800' },
  chipTextActive: { color: '#FFFFFF' },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  confirmButton: {
    alignItems: 'center',
    backgroundColor: '#805E21',
    borderRadius: 16,
    flex: 1,
    paddingVertical: 15,
  },
  confirmText: { color: '#FFFFFF', fontSize: 15, fontWeight: '900' },
  content: {
    alignSelf: 'center',
    gap: 16,
    maxWidth: 760,
    paddingBottom: 60,
    paddingHorizontal: 20,
    paddingTop: 18,
    width: '100%',
  },
  empty: { alignItems: 'center', gap: 8, paddingVertical: 48 },
  emptyTitle: { color: '#18202B', fontSize: 18, fontWeight: '800' },
  error: { color: '#B54747', fontSize: 14, fontWeight: '700' },
  filterButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: '#FFF9ED',
    borderRadius: 14,
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 14,
    paddingVertical: 11,
  },
  filterButtonActive: { backgroundColor: '#805E21' },
  filterText: { color: '#805E21', fontSize: 13, fontWeight: '800' },
  filterTextActive: { color: '#FFFFFF' },
  floatingAddButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.accent,
    borderRadius: 30,
    bottom: 24,
    height: 60,
    justifyContent: 'center',
    position: 'absolute',
    right: 22,
    width: 60,
    zIndex: 10,
    ...goldButtonShadow,
  },
  handle: {
    alignSelf: 'center',
    backgroundColor: '#D2D7DD',
    borderRadius: 99,
    height: 5,
    marginBottom: 16,
    width: 46,
  },
  header: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderBottomColor: '#ECEFF2',
    borderBottomWidth: 1,
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  headerButton: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    width: 44,
    ...goldButtonShadow,
  },
  headerCopy: { flex: 1, marginHorizontal: 12 },
  input: {
    backgroundColor: '#F7F8FA',
    borderColor: '#E2E5E9',
    borderRadius: 15,
    borderWidth: 1,
    color: '#18202B',
    fontSize: 16,
    marginTop: 7,
    paddingHorizontal: 15,
    paddingVertical: 13,
  },
  label: {
    color: '#46505C',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 15,
  },
  list: { gap: 12 },
  movementCard: {
    alignItems: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
  },
  movementIn: { color: '#288B52', fontSize: 17, fontWeight: '900' },
  movementNotes: { color: '#46505C', fontSize: 13, marginTop: 6 },
  movementOut: { color: '#B54747', fontSize: 17, fontWeight: '900' },
  movementValue: { alignItems: 'flex-end', marginLeft: 12 },
  muted: { color: '#6B7480', fontSize: 13, lineHeight: 19 },
  overlay: {
    backgroundColor: 'rgba(17,24,39,0.35)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  photoPicker: {
    alignItems: 'center',
    backgroundColor: '#F7F8FA',
    borderColor: '#E2E5E9',
    borderRadius: 15,
    borderWidth: 1,
    height: 112,
    justifyContent: 'center',
    marginTop: 16,
    overflow: 'hidden',
  },
  orderActions: { flexDirection: 'row', gap: 18 },
  orderCancelButton: { alignSelf: 'flex-start', marginTop: 8 },
  orderCancelText: { color: '#805E21', fontSize: 13, fontWeight: '800' },
  orderTotal: { color: '#18202B', fontSize: 16, fontWeight: '900' },
  deleteSmallButton: { backgroundColor: '#FDECEC' },
  photoPickerImage: { height: '100%', width: '100%' },
  photoPickerLabel: {
    color: '#805E21',
    fontSize: 13,
    fontWeight: '800',
    marginTop: 7,
  },
  productActions: { gap: 8 },
  productCard: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    flexDirection: 'row',
    padding: 15,
  },
  productCopy: { flex: 1, marginHorizontal: 12 },
  productIcon: {
    alignItems: 'center',
    backgroundColor: '#FFF7E7',
    borderRadius: 16,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  productIconAlert: { backgroundColor: '#FDECEC' },
  productImage: { height: '100%', width: '100%' },
  productName: { color: '#18202B', fontSize: 16, fontWeight: '800' },
  pressed: { opacity: 0.74, transform: [{ scale: 0.98 }] },
  removePhoto: { alignSelf: 'flex-start', marginTop: 8 },
  removePhotoLabel: { color: '#B54747', fontSize: 13, fontWeight: '800' },
  reverseButton: { alignSelf: 'flex-start', marginTop: 8 },
  reverseText: { color: '#B54747', fontSize: 13, fontWeight: '800' },
  reversedText: {
    color: '#697386',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 8,
  },
  screen: { backgroundColor: '#F5F6F8', flex: 1 },
  modalKeyboard: { flex: 1 },
  sheet: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  },
  sheetActions: { flexDirection: 'row', gap: 12, marginTop: 24 },
  sheetContent: { padding: 22, paddingBottom: 36 },
  sheetSubtitle: { color: '#6B7480', fontSize: 14, marginTop: 5 },
  sheetTitle: { color: '#18202B', fontSize: 23, fontWeight: '900' },
  smallButton: {
    alignItems: 'center',
    backgroundColor: '#FFF9ED',
    borderRadius: 12,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  stock: { color: '#288B52', fontSize: 13, fontWeight: '700', marginTop: 4 },
  stockAlert: { color: '#B54747' },
  subtitle: { color: '#6B7480', fontSize: 12, marginTop: 2 },
  summaryCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 17,
    flex: 1,
    minWidth: 100,
    padding: 14,
  },
  summaryCardAlert: { backgroundColor: '#FFF1F1' },
  summaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  summaryValue: { color: '#18202B', fontSize: 19, fontWeight: '900' },
  tab: {
    alignItems: 'center',
    borderBottomColor: 'transparent',
    borderBottomWidth: 3,
    flex: 1,
    paddingVertical: 12,
  },
  tabActive: { borderBottomColor: '#805E21' },
  tabText: { color: '#6B7480', fontSize: 14, fontWeight: '700' },
  tabTextActive: { color: '#805E21', fontWeight: '900' },
  tabs: { backgroundColor: '#FFFFFF', flexDirection: 'row' },
  title: { color: appTheme.colors.text, fontSize: 22, fontWeight: '900' },
});
