import { StyleSheet } from 'react-native';

import { appStyles, appTheme, goldButtonShadow } from '../../components/BottomNavigation';

export const styles = StyleSheet.create({
  actionRow: { flexDirection: 'row', gap: 10 },
  screen: appStyles.screen,
  header: { alignItems: 'center', flexDirection: 'row', gap: 12, padding: 20 },
  back: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surfaceMuted,
    borderRadius: 20,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  title: { color: appTheme.colors.text, fontSize: 24, fontWeight: '900' },
  subtitle: { color: appTheme.colors.textMuted, fontSize: 13, marginTop: 2 },
  content: { gap: 14, padding: 20 },
  history: { gap: 8 },
  historyCaption: {
    color: appTheme.colors.textMuted,
    fontSize: 11,
    marginTop: 2,
  },
  historyAmount: {
    color: appTheme.colors.text,
    fontSize: 14,
    fontWeight: '900',
  },
  historyRow: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 14,
    flexDirection: 'row',
    padding: 14,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  historyValue: { alignItems: 'flex-end' },
  metric: { color: appTheme.colors.textMuted, fontSize: 12, fontWeight: '800' },
  metrics: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  balance: {
    backgroundColor: appTheme.colors.surface,
    borderRadius: 24,
    padding: 22,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  balanceLabel: { color: appTheme.colors.textMuted, fontSize: 14 },
  balanceValue: {
    color: appTheme.colors.text,
    fontSize: 38,
    fontWeight: '900',
    marginTop: 8,
  },
  balanceCopy: {
    color: appTheme.colors.textMuted,
    fontSize: 14,
    lineHeight: 20,
    marginTop: 10,
  },
  commissionBalance: {
    backgroundColor: appTheme.colors.surface,
    borderRadius: 20,
    padding: 18,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  commissionMetric: {
    color: appTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: '700',
  },
  commissionMetrics: { flexDirection: 'row', gap: 16, marginTop: 10 },
  commissionSection: { gap: 12 },
  confirmButton: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 14,
    marginTop: 8,
    padding: 15,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  confirmButtonText: {
    color: appTheme.colors.accentDark,
    fontSize: 15,
    fontWeight: '900',
  },
  dangerText: {
    color: appTheme.colors.danger,
    fontSize: 13,
    fontWeight: '900',
  },
  dangerButton: { alignItems: 'center', padding: 12 },
  dateField: { flex: 1 },
  dateRow: { flexDirection: 'row', gap: 10 },
  financialRow: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 14,
    flexDirection: 'row',
    padding: 14,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  financialRowHeader: { alignItems: 'center', flexDirection: 'row' },
  input: {
    borderColor: appTheme.colors.border,
    borderRadius: 12,
    borderWidth: 1,
    color: appTheme.colors.text,
    padding: 12,
  },
  inputLabel: {
    color: appTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
    marginTop: 8,
  },
  linkText: { color: appTheme.colors.accent, fontSize: 13, fontWeight: '900' },
  method: {
    borderColor: appTheme.colors.border,
    borderRadius: 12,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 9,
  },
  methodActive: {
    backgroundColor: appTheme.colors.accentWash,
    borderColor: appTheme.colors.accentWash,
  },
  methodRow: { flexDirection: 'row', gap: 8 },
  methodText: {
    color: appTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  methodTextActive: {
    color: appTheme.colors.text,
    fontSize: 12,
    fontWeight: '900',
  },
  modalBackdrop: { flex: 1 },
  modalRoot: { backgroundColor: 'rgba(0,0,0,0.35)', flex: 1 },
  modalKeyboard: { flex: 1 },
  notesInput: { minHeight: 70, textAlignVertical: 'top' },
  payphoneAction: {
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  payphoneCard: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 19,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    padding: 16,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  payphoneGuide: {
    backgroundColor: appTheme.colors.surfaceMuted,
    borderRadius: 14,
    gap: 8,
    marginTop: 8,
    padding: 14,
  },
  payphoneGuideNote: {
    color: appTheme.colors.textMuted,
    fontSize: 12,
    lineHeight: 17,
  },
  payphoneGuideStep: {
    color: appTheme.colors.text,
    fontSize: 12,
    lineHeight: 18,
  },
  payphoneGuideTitle: {
    color: appTheme.colors.text,
    fontSize: 14,
    fontWeight: '900',
  },
  payphoneSheet: {
    backgroundColor: appTheme.colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    gap: 8,
    marginTop: 'auto',
    padding: 22,
    paddingBottom: 36,
  },
  primaryAction: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 14,
    flex: 1,
    padding: 13,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  primaryActionText: {
    color: appTheme.colors.accentDark,
    fontSize: 12,
    fontWeight: '900',
  },
  professionalChip: {
    backgroundColor: appTheme.colors.surfaceMuted,
    borderRadius: 16,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  professionalChipActive: { backgroundColor: appTheme.colors.accentWash },
  professionalChipText: {
    color: appTheme.colors.textMuted,
    fontSize: 12,
    fontWeight: '800',
  },
  professionalChipTextActive: { color: appTheme.colors.text },
  professionalFilters: { gap: 8 },
  rowButtons: {
    flexDirection: 'row',
    gap: 18,
    justifyContent: 'flex-end',
  },
  secondaryAction: {
    backgroundColor: appTheme.colors.surface,
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    padding: 13,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  secondaryActionText: {
    color: appTheme.colors.accentDark,
    fontSize: 12,
    fontWeight: '900',
  },
  sectionTitle: {
    color: appTheme.colors.text,
    fontSize: 16,
    fontWeight: '900',
  },
  settlementAmount: {
    color: appTheme.colors.text,
    fontSize: 18,
    fontWeight: '900',
  },
  settlementCard: {
    backgroundColor: appTheme.colors.surface,
    borderRadius: 16,
    gap: 9,
    padding: 14,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  sheet: {
    backgroundColor: appTheme.colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    gap: 8,
    padding: 22,
    paddingBottom: 30,
  },
  sheetViewport: {
    backgroundColor: appTheme.colors.surface,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    marginTop: 'auto',
  },
  sheetCopy: { color: appTheme.colors.textMuted, fontSize: 13 },
  sheetTitle: { color: appTheme.colors.text, fontSize: 22, fontWeight: '900' },
  statusText: {
    color: appTheme.colors.textMuted,
    fontSize: 11,
    textTransform: 'capitalize',
  },
  warningCopy: {
    color: appTheme.colors.accentDark,
    fontSize: 12,
    lineHeight: 17,
  },
  tabs: {
    borderBottomColor: appTheme.colors.surfaceMuted,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 25,
    paddingVertical: 12,
  },
  tab: { color: appTheme.colors.textMuted, fontSize: 14, fontWeight: '800' },
  tabActive: { color: appTheme.colors.text, fontSize: 14, fontWeight: '900' },
  card: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surface,
    borderRadius: 19,
    borderWidth: 0,
    flexDirection: 'row',
    gap: 12,
    padding: 16,
    transform: [{ translateY: -3 }],
    ...goldButtonShadow,
  },
  icon: {
    alignItems: 'center',
    backgroundColor: appTheme.colors.surfaceMuted,
    borderRadius: 17,
    height: 50,
    justifyContent: 'center',
    width: 50,
  },
  copy: { flex: 1 },
  cardTitle: { color: appTheme.colors.text, fontSize: 16, fontWeight: '900' },
  cardDescription: {
    color: appTheme.colors.textMuted,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 4,
  },
  badge: {
    backgroundColor: appTheme.colors.border,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  badgeText: {
    color: appTheme.colors.textMuted,
    fontSize: 10,
    fontWeight: '900',
  },
});
